spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/crowndine
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}
    hikari: # Connection poll
      max-lifetime: 300000 # 5 phút
      idle-timeout: 60000 # 1 phút
      validation-timeout: 5000 # 5 giây
      minimum-idle: 5
      maximum-pool-size: 20
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    from: ${MAIL_USERNAME:}
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false