spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/crowndine
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456}
    hikari: # Connection poll
      max-lifetime: 300000 # 5 phút
      idle-timeout: 60000 # 1 phút
      validation-timeout: 5000 # 5 giây
      minimum-idle: 5
      maximum-pool-size: 20
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:dev/db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    from: ${MAIL_USERNAME:dattqde181019@fpt.edu.vn}
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:dattqde181019@fpt.edu.vn}
    password: ${MAIL_PASSWORD:krdmwfrkaizzvgwb}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  access-key: OwOw+8t/PROzQ2jr+ecXe3MGrp5RDjwEN4sj56pd4uo=
  refresh-key: mvBb/s/xhkDlzsYQbMcutG8W9AB2Noqb8GWJapqs66Y=
  access-key-expiration: 600000
  refresh-key-expiration: 100000000

logging:
  level:
    org.flywaydb: DEBUG

#Clooudinary
cloudinary:
  cloud_name: dk1urarrc
  api_key: 654243287352318
  api_secret: IJAoDwzp8EaLRI7KJKYwYHqXqbo

#PayOS
payos:
  client-id: 02745e9c-7c5a-4a1e-81d0-bb50281bec1f
  api-key: a189d0aa-4443-4b62-b1ff-ae64b057a0eb
  checksum-key: 5304c2338d683c8eb7d9734b2ccdecb52016e029d464946f11b8a653971eefc1
  return-url: http://localhost:5173/thanh-toan/thanh-cong
  cancel-url: http://localhost:5173/thanh-toan/that-bai
